[project]
name = "porth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JohnCLlStokes", email = "johnclstokes@hotmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "camau",  # routing
    "fastapi",  # api
    "fastapi[standard]",
    "uvicorn",  # run api locally
    "pydantic",  # schemas
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "ty",
]

[project.scripts]
porth = "porth:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tools.ruff]
select=["ALL"]

